# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrawThriangle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  pod 'GL', :path=> './../../../Libs/GL'
  pod 'GLTools', :path=> './../../../Libs/GLTools'

  # Pods for DrawThriangle

end
